Repository ieeessitvit/Machine-learning, pull requests merged in 2020-10, with the labels that each got.

#11 added naives bayes classification
  classification/Naive-Bayes-classifier/mynaive.py
  classification/Naive-Bayes-classifier/pima-indians-diabetes.csv
Labels: enhancement, good first issue, hacktober-accepted

#13 Using NEAT Algorithm to play Flappy Bird
  Reinforcement Learning/NEAT Algorithm/FlappyBird/FlappyBirdWorkigFile.py
  Reinforcement Learning/NEAT Algorithm/FlappyBird/config-feedforward.txt
  Reinforcement Learning/NEAT Algorithm/FlappyBird/imgs/base.png
  Reinforcement Learning/NEAT Algorithm/FlappyBird/imgs/bg.png
  Reinforcement Learning/NEAT Algorithm/FlappyBird/imgs/bird1.png
  Reinforcement Learning/NEAT Algorithm/FlappyBird/imgs/bird2.png
  Reinforcement Learning/NEAT Algorithm/FlappyBird/imgs/bird3.png
  Reinforcement Learning/NEAT Algorithm/FlappyBird/imgs/pipe.png
Labels: enhancement, good first issue, hacktober-accepted

#12 Added LSTM model for natural language processing
  Natural Language Processing/LSTM/Dataset/data_train.csv
  Natural Language Processing/LSTM/LSTM.py
Labels: enhancement, good first issue, hacktober-accepted

#25 Added Red wine quality prediction
  classification/k Nearest  Neighbors/Red wine quality prediction.ipynb
Labels: enhancement, good first issue, hacktober-accepted

#26 Added Introduction to Tensorflow
  Deep Learning/Image Dehazing using Tensorflow/TensorFlow_Introduction.ipynb
  data science notebooks/A Network Analysis of Game of Thrones_notebook.ipynb
  data science notebooks/The Android App Market on Google Play_notebook (1).ipynb
  data science notebooks/blockchain and crypto project.ipynb
Labels: enhancement, hacktober-accepted

#28 restr review nlp
  Natural Language Processing/Restaurant_Reviews.tsv
  Natural Language Processing/natural_language_processing.py
Labels: enhancement, good first issue, hacktober-accepted

#27 Added Coursera Machine Learning Programming Assignement Week 2
  regression/Cousera Machine Learning Programming Assignement week2/debug.log
  regression/Cousera Machine Learning Programming Assignement week2/ex1.pdf
  regression/Cousera Machine Learning Programming Assignement week2/ex1/computeCost.m
  regression/Cousera Machine Learning Programming Assignement week2/ex1/computeCostMulti.m
  regression/Cousera Machine Learning Programming Assignement week2/ex1/ex1.m
  regression/Cousera Machine Learning Programming Assignement week2/ex1/ex1_multi.m
  regression/Cousera Machine Learning Programming Assignement week2/ex1/ex1data1.txt
  regression/Cousera Machine Learning Programming Assignement week2/ex1/ex1data2.txt
  regression/Cousera Machine Learning Programming Assignement week2/ex1/featureNormalize.m
  regression/Cousera Machine Learning Programming Assignement week2/ex1/gradientDescent.m
  regression/Cousera Machine Learning Programming Assignement week2/ex1/gradientDescentMulti.m
  regression/Cousera Machine Learning Programming Assignement week2/ex1/lib/jsonlab/AUTHORS.txt
  regression/Cousera Machine Learning Programming Assignement week2/ex1/lib/jsonlab/ChangeLog.txt
  regression/Cousera Machine Learning Programming Assignement week2/ex1/lib/jsonlab/LICENSE_BSD.txt
  regression/Cousera Machine Learning Programming Assignement week2/ex1/lib/jsonlab/README.txt
  regression/Cousera Machine Learning Programming Assignement week2/ex1/lib/jsonlab/jsonopt.m
  regression/Cousera Machine Learning Programming Assignement week2/ex1/lib/jsonlab/loadjson.m
  regression/Cousera Machine Learning Programming Assignement week2/ex1/lib/jsonlab/loadubjson.m
  regression/Cousera Machine Learning Programming Assignement week2/ex1/lib/jsonlab/mergestruct.m
  regression/Cousera Machine Learning Programming Assignement week2/ex1/lib/jsonlab/savejson.m
  regression/Cousera Machine Learning Programming Assignement week2/ex1/lib/jsonlab/saveubjson.m
  regression/Cousera Machine Learning Programming Assignement week2/ex1/lib/jsonlab/varargin2struct.m
  regression/Cousera Machine Learning Programming Assignement week2/ex1/lib/makeValidFieldName.m
  regression/Cousera Machine Learning Programming Assignement week2/ex1/lib/submitWithConfiguration.m
  regression/Cousera Machine Learning Programming Assignement week2/ex1/normalEqn.m
  regression/Cousera Machine Learning Programming Assignement week2/ex1/plotData.m
  regression/Cousera Machine Learning Programming Assignement week2/ex1/submit.m
  regression/Cousera Machine Learning Programming Assignement week2/ex1/token.mat
  regression/Cousera Machine Learning Programming Assignement week2/ex1/warmUpExercise.m
Labels: documentation, enhancement

#29 Added early-detection-of-covid-19-from-chest-x-ray-cnn
  Deep Learning/Image Dehazing using Tensorflow/Covid-CT-Lung.ipynb
  Deep Learning/Image Dehazing using Tensorflow/early-detection-of-covid-19-from-chest-x-ray-cnn.ipynb
Labels: enhancement, good first issue, hacktober-accepted

#30 Added Data_analysis_to_study_COVID_19_and_it's_protein & Image Classification
  Deep Learning/Image Dehazing using Tensorflow/MNIST - Image Classification.ipynb
  classification/Naive-Bayes-classifier/Mushroom Naive Bayes.ipynb
  data science notebooks/Data_analysis_to_study_COVID_19_and_it's_protein.ipynb
Labels: enhancement, hacktober-accepted

#31 Regression algorithms for crop prediction
  regression/Crop_Prediction.ipynb
Labels: enhancement, good first issue

#33 Added a Fake News Classifier
  classification/Passive Aggressive Classifier/Fake News Classifier.ipynb
  classification/Passive Aggressive Classifier/README.md
Labels: enhancement, good first issue, hacktober-accepted
